# Generated by Django 4.1.7 on 2024-01-03 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_subfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='subfolder',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.folder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subfolder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
