# Generated by Django 4.1.7 on 2024-01-03 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_subfolder_folder_alter_subfolder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_folder', to='home.folder'),
        ),
        migrations.DeleteModel(
            name='SubFolder',
        ),
    ]
