# Generated by Django 4.1.7 on 2024-01-03 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_folder_folder_subfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfolder',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subfolder'),
        ),
    ]
