# Generated by Django 4.1.7 on 2024-01-03 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_subfolder_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='home.folder'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubFolder',
        ),
    ]
